---
title: "Exploratory_Analysis_Enrollment_Data_Candice"
author: "Candice Yu"
date: "2022-12-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Installation of Biobase and NMF
```{r}
#if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

#BiocManager::install("Biobase")

library(Biobase)

#install.packages("CRAN")
#install.packages("NMF")
# Load
library(NMF)
```

# Enrollment Data Import 
```{r}
## 1. Read data 
#install.packages("readxl")
library("readxl")
Enrollment <- read_excel(paste0("/Users/candiceyu/Documents/PSTAT296B/Data/", 
                                  "Enrollment_Data_2019-2022.xlsx"))

## 2. Used the contract ID and plan ID combined as the unique ID and add up all enrollment for each year. 

#install.packages("dplyr")
library("dplyr")
Enrollment_ByID <- Enrollment %>%
  group_by(Contract_Number, Plan_ID, Year) %>% 
  transmute(Enrollment=sum(Enrollment)) %>%
  distinct()

## 3. Combine the contract ID and Plan ID into one column 
Enrollment_ByID$Contract_Plan <- paste0(Enrollment_ByID$Contract_Number, "-",
                                                           Enrollment_ByID$Plan_ID)

Enrollment_ByID <- Enrollment_ByID[,c(5,1,2,3,4)]
head(Enrollment_ByID)
```

# Growth Plots for the Enrollment Data
```{r fig.align="center", fig.height=8, fig.width=10}
require(ggplot2)

## 1. Drop plans with only one observation
Enrollment_ByID_GP<- Enrollment_ByID %>% 
  group_by(Contract_Plan) %>%
  filter(n()>1)

## 2. Separated Growth Plots
ggplot(data = Enrollment_ByID, aes(x = Year, y = Enrollment, color = Contract_Number)) +
  geom_point() +
  facet_wrap(~ Contract_Plan) +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) + 
  facet_wrap(~ Contract_Plan) +
  labs(title = "Changes in Enrollment from 2019 to 2022",
       x = "Year",
       y = "Enrollment",
       color = NULL)

```
```{r fig.align="center", fig.height=6, fig.width=8}
enrollment <- read.csv("/Users/candiceyu/Documents/PSTAT296B/Code/Benefits_Enrollment_Eligibles.csv")
enrollment$Year <- enrollment$Year-rep(2018, length(enrollment$Year))
## 2. Separated Growth Plots
ggplot(data = enrollment, aes(x = Year, y = State_Enrollment, color = Contract_ID)) +
  geom_point() +
  facet_wrap(~ Contract_Plan_Segment) +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) + 
  labs(title = "Changes in Enrollment from 2019 to 2022",
       x = "Year",
       y = "Enrollment",
       color = NULL)

```

```{r fig.align="center", fig.height=8, fig.width=10}
## 3. Single Growth Plot
ggplot(data = Enrollment_ByID_GP, aes(x = Year, y = Enrollment, color = Contract_Plan)) + 
  geom_line() +
  labs(title = "Changes in Enrollment from 2019 to 2022",
       x = "Year",
       y = "Enrollment",
       color = NULL)

```



# Generate a table indicating the number of observations per year per contract in the data
## The summary table for enrollment grouped by years

```{r}
# load the library
#install.packages("psych")
library(psych) 
# get the summary table for enrollment grouped by years
a <- describeBy(Enrollment_ByID$Enrollment, group=Enrollment_ByID$Year, fast=TRUE)

a_2019 <- as.data.frame(a$`2019`)
a_2020 <- as.data.frame(a$`2020`)
a_2021 <- as.data.frame(a$`2021`)
a_2022 <- as.data.frame(a$`2022`)
Summrary_ByYear <- rbind(a_2019, a_2020, a_2021, a_2022) 

Summrary_ByYear <-Summrary_ByYear %>% 
  select(-c(vars))

rownames(Summrary_ByYear) = c("2019","2020","2021","2022")
Summrary_ByYear

```
```{r}
# load the library
#install.packages("psych")
library(psych) 
# get the summary table for enrollment grouped by years
a <- describeBy(enrollment$State_Enrollment, group=enrollment$Year, fast=TRUE)

a_2019 <- as.data.frame(a$`2019`)
a_2020 <- as.data.frame(a$`2020`)
a_2021 <- as.data.frame(a$`2021`)
a_2022 <- as.data.frame(a$`2022`)
Summrary_ByYear <- rbind(a_2019, a_2020, a_2021, a_2022) 

Summrary_ByYear <-Summrary_ByYear %>% 
  select(-c(vars))

rownames(Summrary_ByYear) = c("2019","2020","2021","2022")
Summrary_ByYear

```

```{r}
library(ggplot2)
## 1. Boxplots
Enrollment_ByID$Year <- as.factor(Enrollment_ByID$Year)
ggplot(Enrollment_ByID, aes(x = Year, y = Enrollment, group = Year, fill = Year)) + 
  geom_boxplot() +
  stat_summary(fun = "mean", geom = "point", shape = 8,
               size = 2, color = "white")+
  labs(title = "Boxplots for Enrollment by Years",
       x = "Year",
       y = "Enrollment")+
    theme(legend.position = "none")


## 2. Extracting the statistical summary from the boxplots

Enrollment_ByID %>% 
  group_by(Enrollment, Year) %>% 
  summary()

tapply(Enrollment_ByID$Enrollment, Enrollment_ByID$Year, summary)  



```

```{r}
library(ggplot2)
## 1. Boxplots
enrollment$Year <- as.factor(enrollment$Year)
ggplot(enrollment, aes(x = Year, y = State_Enrollment, group = Year, fill = Year)) + 
  geom_boxplot() +
  stat_summary(fun = "mean", geom = "point", shape = 8,
               size = 2, color = "white")+
  labs(title = "Boxplots for Enrollment by Years",
       x = "Year",
       y = "Enrollment")+
    theme(legend.position = "none")
## 2. Extracting the statistical summary from the boxplots

Boxplot_Enrollment <- boxplot(Enrollment~Year, data = Enrollment_ByID)
Summary_Boxplot<- Boxplot_Enrollment$stats
colnames(Summary_Boxplot)<-c("2019","2020","2021","2022")
rownames(Summary_Boxplot)<-c("Min","First Quartile","Median","Third Quartile","Maximum")
Summary_Boxplot

```

# Histogram of Enrollment 
```{r}
library(plyr)
mu <- ddply(Enrollment_ByID, "Year", summarise, grp.mean=mean(Enrollment))
head(mu)


library(ggplot2)
His_By_Year <- ggplot(Enrollment_ByID, aes(x = Enrollment, color=Year))+
  geom_histogram(fill="white", bins = 20)+
  facet_grid(Year ~ .)+
  geom_vline(data=mu, aes(xintercept=grp.mean, color="red"),
             linetype="dashed") + # Add mean lines
  theme(legend.position = "none")+
  labs(title = "Histograms for Enrollment by Years",
       x = "Enrollment",
       y = "Frequency")


His_By_Year
```

# Histogram of Enrollment 
```{r}
library(plyr)
mu <- ddply(enrollment, "Year", summarise, grp.mean=mean(State_Enrollment))
head(mu)

library(ggplot2)
enrollment$Year <- as.factor(enrollment$Year)
His_By_Year <- ggplot(enrollment, aes(x = State_Enrollment, color=Year))+
  geom_histogram(fill="white", bins = 20)+
  facet_grid(Year ~ .)+
  geom_vline(data=mu, aes(xintercept=grp.mean, color="red"),
             linetype="dashed") + # Add mean lines
  theme(legend.position = "none")+
  labs(title = "Histograms for Enrollment by Years",
       x = "Enrollment",
       y = "Frequency")


His_By_Year
  
```

